/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_appsync_graphqlEndpoint:
        'https://h337i462yzccnfgfzpf7gl2cau.appsync-api.us-east-1.amazonaws.com/graphql',
    aws_appsync_region: 'us-east-1',
    aws_appsync_authenticationType: 'API_KEY',
    aws_appsync_apiKey: 'da2-2kt2xg55bjc6vio7d2rsarbkou',
    aws_cognito_identity_pool_id:
        'us-east-1:e51fff87-bc33-43d8-93bc-5dd2623dbd5e',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_OTS2Ch8ot',
    aws_user_pools_web_client_id: '6v2vpdu8do7r2ue49r53tm26aj',
    oauth: {},
    aws_cognito_username_attributes: ['EMAIL'],
    aws_cognito_social_providers: [],
    aws_cognito_signup_attributes: [
        'EMAIL',
        'GIVEN_NAME',
        'FAMILY_NAME',
        'PHONE_NUMBER',
    ],
    aws_cognito_mfa_configuration: 'OFF',
    aws_cognito_mfa_types: ['SMS'],
    aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: 8,
        passwordPolicyCharacters: [
            'REQUIRES_LOWERCASE',
            'REQUIRES_NUMBERS',
            'REQUIRES_SYMBOLS',
            'REQUIRES_UPPERCASE',
        ],
    },
    aws_cognito_verification_mechanisms: ['EMAIL'],
    aws_user_files_s3_bucket:
        'benefibackendv2cd5ab8b7d965462d89125e4306d1a1fa125905-dev',
    aws_user_files_s3_bucket_region: 'us-east-1',
};

export default awsmobile;
